name: notify on suite failed

on: [push]

jobs:
  notify-on-failure-job:
    name: Notify on failure
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Wait for pass suite to conclude
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.ref }}
          running-workflow-name : 'Notify on failure'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Notify slack on failure
#        https://github.community/t/continue-on-error-allow-failure-ui-indication/16773/15
#        https://docs.github.com/en/actions/learn-github-actions/contexts
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           SLACK_MESSAGE: 'Deployment failed'
