name: Notify on commit status failed
on:
  push:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
  
jobs:
  notify-on-commit-status-failed:
    name: Notify on commit status failed
    runs-on: ubuntu-latest
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: WyriHaximus/github-action-wait-for-status@v1.4
        with:
          ignoreActions: "Automerge PRs" ## Note that these names are the human readable names use as status on commits, and show up as status checks on PRs.
          checkInterval: 13
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Notify slack on failure
#        https://github.community/t/continue-on-error-allow-failure-ui-indication/16773/15
#        https://docs.github.com/en/actions/learn-github-actions/contexts
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           SLACK_MESSAGE: 'Deployment failed ${{ steps.waitforstatuschecks.outputs }}'
