name: notify on deployment failed

on:
  deployment:
    branches: main

jobs:
  notify-on-deployment-failure:
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    name: Notify on deployment failure
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack on failure
#        https://github.community/t/continue-on-error-allow-failure-ui-indication/16773/15
#        https://docs.github.com/en/actions/learn-github-actions/contexts
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           SLACK_MESSAGE: 'Deployment failed ${{ steps.wait.outputs }}'
